"""
AI-generated code fingerprinting.

Detects code segments likely written by AI tools (GitHub Copilot, Cursor,
ChatGPT, Claude, Gemini, Codeium, Tabnine) using commit metadata, structural
heuristics, security-specific antipatterns, and pattern analysis.

Scoring model (weights sum to 1.0):
  commit_signals    0.30  — AI tool attribution in git metadata
  code_patterns     0.25  — structural markers (TODO, broad catch, over-comment)
  security_apats    0.25  — AI-characteristic security mistakes
  comment_density   0.10  — elevated comment-to-code ratio
  placeholder_strs  0.05  — dummy/placeholder literal values
  method_validity   0.05  — calls to undefined methods (phantom hallucinations)
"""

import logging
import re

from vulnchain.analysis.models import AICodeSegment
from vulnchain.ingestion.models import CommitInfo, SourceFile

logger = logging.getLogger(__name__)

# ── Commit-level signals ──────────────────────────────────────────────────────

_AI_COMMIT_RE = re.compile(
    r"(co-authored-by:\s*(github copilot|cursor|codeium|tabnine|amazon q|"
    r"gemini code assist)|"
    r"generated by (copilot|cursor|chatgpt|claude|gemini|codeium|tabnine|ai)|"
    r"ai-assisted|ai.generated|llm.generated|"
    r"suggested by (copilot|github copilot)|"
    r"\[cursor\]|\[copilot\]|\[ai\])",
    re.IGNORECASE,
)

# Large atomic additions in a single commit to few files (AI dump pattern)
_LARGE_ATOMIC_THRESHOLD = 50  # lines added
_LARGE_ATOMIC_FILE_LIMIT = 2  # max files in that commit

# ── Code-pattern signals ──────────────────────────────────────────────────────

_TODO_RE = re.compile(
    r"(//|#)\s*(TODO|FIXME):\s*(add error handling|implement|TODO|placeholder|stub|"
    r"handle this|not implemented|fill in|complete this|add validation|add logging)",
    re.IGNORECASE,
)

_BROAD_CATCH_RE = re.compile(
    # C-family: catch(Exception ...) / catch(Error ...) / catch(Throwable ...)
    r"catch\s*\(\s*(Exception|Error|Throwable|BaseException)\s*[\w]*\s*\)"
    r"|"
    # Python: bare except or except Exception
    r"^\s*except\s*(?:Exception|BaseException)?(?:\s+as\s+\w+)?\s*:\s*(?:pass|#.*)?$",
    re.IGNORECASE | re.MULTILINE,
)

_GENERIC_VAR_RE = re.compile(
    # Only flag when used as an assignment target (= on same line),
    # and only single-word names (not result_set, response_data, etc.)
    r"\b(result|response|data|temp|obj|value|item)\s*=",
    re.IGNORECASE,
)

_OVER_COMMENT_RE = re.compile(
    r"(//|#)\s+(?:This (?:method|function|code|class|endpoint|handler)\s+|"
    r"The following\s+|We (?:first|then|next|finally)\s+|"
    r"This will\s+|Here we\s+|Note that\s+|This is a\s+|"
    r"This (?:ensures|checks|validates|handles|creates|returns|initializes)\s+)",
    re.IGNORECASE,
)

# ── Security antipattern signals (highly specific to AI tools) ────────────────

_SSL_VERIFY_DISABLED_RE = re.compile(
    r"verify\s*=\s*False"
    r"|InsecureSkipVerify\s*(?::|=)\s*true"
    r"|ssl\._create_unverified_context\s*\(\s*\)"
    r"|check_hostname\s*=\s*False"
    r"|VERIFY_SSL\s*=\s*False"
    r"|SSL_VERIFY\s*=\s*False",
    re.IGNORECASE,
)

# Placeholder/example secret values that AI tools produce in examples
_PLACEHOLDER_SECRET_RE = re.compile(
    r"""['"]("""
    r"""your[-_]?(?:secret|api[-_]?key|token|password|key|access[-_]?key|private[-_]?key)|"""
    r"""changeme|change[-_]me|change_this|"""
    r"""password123|pass(?:word)?123|admin123|secret123|test[-_]?(?:key|secret|token)|"""
    r"""my[-_]?(?:secret|password|key|token)|"""
    r"""supersecretkey|verysecretkey|hardcoded[-_]?secret|"""
    r"""insert[-_]?(?:your|api|secret)|replace[-_]?(?:with|me)|"""
    r"""todo[-_]?(?:replace|insert|fill)|placeholder[-_]?(?:key|secret|token)"""
    r""")['"]\s*""",
    re.IGNORECASE,
)

# AI uses SHA-256/MD5 for password hashing instead of bcrypt/argon2
_WEAK_PASSWORD_HASH_RE = re.compile(
    r"hashlib\.(md5|sha1|sha256|sha512)\s*\(\s*(?:password|passwd|pwd|pass)\b",
    re.IGNORECASE,
)

# JWT without signature verification — AI frequently produces this
_JWT_NO_VERIFY_RE = re.compile(
    r"""algorithms\s*=\s*\[["']none["']\]"""
    r"""|verify_signature['":\s]*False"""
    r"""|options\s*=\s*\{[^}]*verify_signature['":\s]*False"""
    r"""|jwt\.decode\s*\([^)]*,\s*None\s*[,)]""",
    re.IGNORECASE,
)

# Timing attack: token comparison with == (AI misses constant-time compare)
_TIMING_UNSAFE_COMPARE_RE = re.compile(
    r"\b(?:token|secret|hmac|signature|hash|digest)\b[^=\n]*==\s*"
    r"|==\s*[^=\n]*\b(?:token|secret|hmac|signature|hash|digest)\b",
    re.IGNORECASE,
)

# ── Placeholder literal strings ───────────────────────────────────────────────

_PLACEHOLDER_LITERAL_RE = re.compile(
    r"""['"](?:"""
    r"""example\.com|http://localhost(?::\d+)?(?:/[^\s'"]*)?|"""
    r"""0\.0\.0\.0|127\.0\.0\.1|"""
    r"""dummy[-_]?(?:key|secret|token|data|value|user|password|url)|"""
    r"""test[-_]?(?:user|admin|value|data)|"""
    r"""admin(?:@example\.com)?|"""
    r"""foo|bar|baz|qux|foobar|"""
    r"""xxx+|aaa+|zzz+"""
    r""")['"]\s*""",
    re.IGNORECASE,
)

# ── Comment-density helpers ───────────────────────────────────────────────────

_COMMENT_PATTERNS: dict[str, re.Pattern] = {
    "python": re.compile(r"^\s*#"),
    "javascript": re.compile(r"^\s*(?://|/\*)"),
    "typescript": re.compile(r"^\s*(?://|/\*)"),
    "java": re.compile(r"^\s*(?://|/\*)"),
    "csharp": re.compile(r"^\s*(?://|/\*)"),
    "go": re.compile(r"^\s*//"),
    "rust": re.compile(r"^\s*//"),
    "php": re.compile(r"^\s*(?://|#|/\*)"),
    "swift": re.compile(r"^\s*(?://|/\*)"),
    "kotlin": re.compile(r"^\s*(?://|/\*)"),
    "ruby": re.compile(r"^\s*#"),
}

# ── Stdlib method whitelist ───────────────────────────────────────────────────

_STDLIB: frozenset[str] = frozenset(
    [
        "append",
        "extend",
        "get",
        "set",
        "add",
        "remove",
        "split",
        "join",
        "strip",
        "replace",
        "format",
        "encode",
        "decode",
        "read",
        "write",
        "close",
        "open",
        "print",
        "log",
        "info",
        "warning",
        "error",
        "debug",
        "upper",
        "lower",
        "startswith",
        "endswith",
        "keys",
        "values",
        "items",
        "update",
        "pop",
        "insert",
        "sort",
        "filter",
        "map",
        "any",
        "all",
        "len",
        "str",
        "int",
        "float",
        "list",
        "dict",
        "tuple",
        "type",
        "isinstance",
        "hasattr",
        "getattr",
        "setattr",
        "delattr",
        "isinstance",
        "issubclass",
        "callable",
        "iter",
        "next",
        "enumerate",
        "zip",
        "reversed",
        "sorted",
        "sum",
        "min",
        "max",
        "abs",
        "round",
        "hash",
        "id",
        "repr",
        "vars",
        "dir",
        "input",
        "output",
        "flush",
        "seek",
        "tell",
        "readline",
        "readlines",
        "writelines",
        "truncate",
        "connect",
        "execute",
        "fetchone",
        "fetchall",
        "fetchmany",
        "commit",
        "rollback",
        "cursor",
        "bind",
        "listen",
        "accept",
        "recv",
        "send",
        "sendall",
        "shutdown",
        "getsockname",
        "getpeername",
        "settimeout",
        "copy",
        "deepcopy",
        "dumps",
        "loads",
        "dump",
        "load",
        "match",
        "search",
        "findall",
        "finditer",
        "sub",
        "subn",
        "compile",
        "raise",
        "assert",
        "return",
        "yield",
        "raise_for_status",
        "json",
        "text",
        "content",
        "status_code",
        "headers",
        "cookies",
        "run",
        "start",
        "stop",
        "reset",
        "init",
        "setup",
        "teardown",
        "configure",
        "verify",
        "validate",
        "sanitize",
        "escape",
        "unescape",
        "serialize",
        "deserialize",
        "encode",
        "decode",
        "compress",
        "decompress",
        "render",
        "redirect",
        "abort",
        "flash",
        "send_file",
        "make_response",
    ]
)

MIN_CONFIDENCE = 0.35


# ── Individual scorers ────────────────────────────────────────────────────────


def _score_commit_signals(file_path: str, commits: list[CommitInfo]) -> tuple[float, list[str]]:
    """Score based on git commit metadata indicating AI authorship."""
    signals: list[str] = []
    score = 0.0

    for commit in commits:
        if file_path not in commit.files_changed:
            continue

        # Explicit AI tool attribution in commit message
        if _AI_COMMIT_RE.search(commit.message):
            signals.append(f"Commit {commit.sha[:8]}: AI tool attribution in message")
            score += 0.55

        # Large atomic addition — AI generates whole files at once
        if commit.additions > _LARGE_ATOMIC_THRESHOLD and len(commit.files_changed) <= _LARGE_ATOMIC_FILE_LIMIT:
            signals.append(
                f"Commit {commit.sha[:8]}: large atomic addition "
                f"({commit.additions}+ lines in {len(commit.files_changed)} file(s))"
            )
            score += 0.25

        # Very large addition with no deletions — typical of pasting AI output
        if commit.additions > 150 and commit.deletions == 0:
            signals.append(
                f"Commit {commit.sha[:8]}: {commit.additions} additions, 0 deletions (full AI-generated dump pattern)"
            )
            score += 0.20

    return min(score, 1.0), signals


def _score_code_patterns(content: str, file_path: str) -> tuple[float, list[str]]:
    """Score based on structural code patterns characteristic of AI output."""
    signals: list[str] = []
    score = 0.0
    lines = content.splitlines()
    total = max(len(lines), 1)

    # TODO/FIXME placeholders with specific AI-generated wording
    todo_count = sum(1 for ln in lines if _TODO_RE.search(ln))
    if todo_count > 0:
        signals.append(f"{todo_count} AI-style TODO/placeholder comment(s)")
        score += 0.15 * min(todo_count, 3)

    # Broad exception catches (AI almost always catches Exception broadly)
    broad_catch = sum(1 for ln in lines if _BROAD_CATCH_RE.search(ln))
    if broad_catch > 0:
        signals.append(f"{broad_catch} broad exception catch(es)")
        score += 0.12 * min(broad_catch, 3)

    # Generic variable names at high density
    generic_count = sum(1 for ln in lines if _GENERIC_VAR_RE.search(ln))
    if generic_count / total > 0.07:
        signals.append(f"High generic variable density ({generic_count}/{total} lines = {generic_count / total:.0%})")
        score += 0.18

    # Over-explanatory comments (AI narrates what code does step-by-step)
    over_comment = sum(1 for ln in lines if _OVER_COMMENT_RE.search(ln))
    if over_comment > 2:
        signals.append(f"{over_comment} over-explanatory inline comments")
        score += 0.15

    # Docstring on every function — AI documents everything
    func_re = re.compile(r"^\s*(?:def |async def |public |private |protected |func )\w+", re.MULTILINE)
    func_count = len(func_re.findall(content))
    docstring_re = re.compile(r'^\s*(?:"""|\'\'\').*?(?:"""|\'\'\')|\s*"""', re.MULTILINE | re.DOTALL)
    docstring_count = len(docstring_re.findall(content))
    if func_count > 3 and docstring_count >= func_count:
        signals.append(f"Every function has a docstring ({docstring_count} docstrings / {func_count} functions)")
        score += 0.12

    # Empty stub functions — body is docstring + pass or NotImplementedError (AI scaffold)
    stub_re = re.compile(
        r"def\s+\w+\s*\([^)]*\)\s*(?:->[^:]+)?\s*:\s*\n"
        r"(?:\s+(?:\"\"\"[^\"]*\"\"\"|\'\'\'[^\']*\'\'\')\s*\n)?"
        r"\s+(?:pass|raise\s+NotImplementedError)\b",
        re.MULTILINE,
    )
    stub_count = len(stub_re.findall(content))
    if stub_count >= 2:
        signals.append(f"{stub_count} empty stub function(s) (scaffold pattern)")
        score += min(0.10 * stub_count, 0.25)

    # Burstiness: low line-length variance = AI uniformity (AAAI 2024)
    non_blank = [len(ln) for ln in lines if ln.strip()]
    if len(non_blank) >= 30:
        mean_len = sum(non_blank) / len(non_blank)
        if mean_len > 1:
            std_len = (sum((ln - mean_len) ** 2 for ln in non_blank) / len(non_blank)) ** 0.5
            cv = std_len / mean_len
            if cv < 0.35:
                signals.append(
                    f"Low line-length variance (CV={cv:.2f}) — uniformly structured, characteristic of AI generation"
                )
                score += 0.25
            elif cv < 0.45:
                signals.append(f"Below-average line-length variance (CV={cv:.2f})")
                score += 0.10

    return min(score, 1.0), signals


def _score_security_antipatterns(content: str) -> tuple[float, list[str]]:
    """
    Score based on AI-characteristic security mistakes.

    AI tools reliably produce specific insecure patterns:
    - Disable SSL verification in examples
    - Placeholder/example credential values
    - Wrong crypto for passwords (SHA-256 instead of bcrypt)
    - JWT without signature verification
    - Timing-unsafe secret comparisons
    """
    signals: list[str] = []
    score = 0.0
    lines = content.splitlines()

    # SSL/TLS verification disabled — AI commonly does this in "examples"
    ssl_disabled = sum(1 for ln in lines if _SSL_VERIFY_DISABLED_RE.search(ln))
    if ssl_disabled > 0:
        signals.append(f"{ssl_disabled} instance(s) of SSL verification disabled (verify=False pattern)")
        score += 0.40

    # Placeholder secret values (very high confidence signal)
    placeholder_creds = sum(1 for ln in lines if _PLACEHOLDER_SECRET_RE.search(ln))
    if placeholder_creds > 0:
        signals.append(f"{placeholder_creds} placeholder/example credential value(s) detected")
        score += 0.45

    # SHA-256/MD5 used for password hashing (should be bcrypt/argon2)
    weak_pw_hash = sum(1 for ln in lines if _WEAK_PASSWORD_HASH_RE.search(ln))
    if weak_pw_hash > 0:
        signals.append(f"{weak_pw_hash} instance(s) of weak algorithm for password hashing")
        score += 0.35

    # JWT without signature verification
    jwt_no_verify = sum(1 for ln in lines if _JWT_NO_VERIFY_RE.search(ln))
    if jwt_no_verify > 0:
        signals.append(f"{jwt_no_verify} JWT decode without signature verification")
        score += 0.35

    # Timing-unsafe token comparison
    timing_unsafe = sum(1 for ln in lines if _TIMING_UNSAFE_COMPARE_RE.search(ln))
    if timing_unsafe > 0:
        signals.append(f"{timing_unsafe} timing-unsafe secret/token comparison (== instead of hmac.compare_digest)")
        score += 0.20

    return min(score, 1.0), signals


def _score_comment_density(content: str, language: str) -> tuple[float, list[str]]:
    """
    Score based on comment-to-code line ratio.

    AI-generated code has significantly higher comment density than human code.
    Typical human code: ~8-12% comment lines.
    AI-generated code: often 20-40%+ comment lines.
    """
    lines = content.splitlines()
    total = len(lines)
    if total < 15:
        return 0.0, []

    pattern = _COMMENT_PATTERNS.get(language)
    if not pattern:
        return 0.0, []

    comment_lines = sum(1 for ln in lines if pattern.match(ln))
    ratio = comment_lines / total

    if ratio >= 0.30:
        return 0.7, [
            f"Very high comment density: {comment_lines}/{total} lines ({ratio:.0%}) — AI tools over-document code"
        ]
    if ratio >= 0.20:
        return 0.35, [f"Elevated comment density: {comment_lines}/{total} lines ({ratio:.0%})"]
    return 0.0, []


def _score_placeholder_strings(content: str) -> tuple[float, list[str]]:
    """
    Score based on placeholder/example literal strings.

    AI tools insert example values (example.com, localhost, dummy_key) that
    humans typically replace before committing.
    """
    signals: list[str] = []
    score = 0.0
    lines = content.splitlines()

    placeholder_count = sum(1 for ln in lines if _PLACEHOLDER_LITERAL_RE.search(ln))
    if placeholder_count >= 3:
        signals.append(f"{placeholder_count} placeholder/example literal strings found")
        score = 0.50
    elif placeholder_count >= 1:
        signals.append(f"{placeholder_count} placeholder/example literal string(s) found")
        score = 0.25

    return min(score, 1.0), signals


def _score_method_validity(content: str, language: str) -> tuple[float, list[str]]:
    """
    Score based on calls to methods not defined in this file or the stdlib.

    AI hallucinates method names that look plausible but don't exist.
    We limit this check to languages where we can reliably parse definitions,
    and only flag when there are many phantom calls (to reduce false positives
    from cross-module method calls).
    """
    signals: list[str] = []
    score = 0.0

    defined: set[str] = set()
    if language == "python":
        for m in re.finditer(r"^\s*(?:async\s+)?def\s+(\w+)\s*\(", content, re.MULTILINE):
            defined.add(m.group(1))
    elif language in ("csharp", "java", "kotlin"):
        for m in re.finditer(
            r"(?:public|private|protected|internal|static|async|override)\s+\S+\s+(\w+)\s*\(",
            content,
        ):
            defined.add(m.group(1))

    if not defined:
        return 0.0, []

    # Extract imported names to exclude from phantom check
    imported: set[str] = set()
    for m in re.finditer(r"^(?:from\s+\S+\s+)?import\s+([\w,\s]+)", content, re.MULTILINE):
        for name in re.split(r"[\s,]+", m.group(1)):
            if name.strip():
                imported.add(name.strip())

    called: set[str] = set()
    for m in re.finditer(r"\b(\w+)\.(\w+)\s*\(", content):
        method_name = m.group(2)
        if method_name not in _STDLIB and method_name not in imported:
            called.add(method_name)

    phantom = called - defined - imported
    # Use a higher threshold (5+) to reduce cross-module false positives
    if len(phantom) > 5:
        signals.append(f"{len(phantom)} calls to potentially undefined methods: " + ", ".join(sorted(phantom)[:6]))
        score += 0.20

    return min(score, 1.0), signals


# ── Main entry point ──────────────────────────────────────────────────────────


def detect_ai_code(
    source_files: list[SourceFile],
    commits: list[CommitInfo],
) -> list[AICodeSegment]:
    """
    Detect AI-generated code segments across all source files.

    Runs six independent scorers and combines them with fixed weights.
    Returns segments with confidence >= MIN_CONFIDENCE, sorted descending.
    """
    segments: list[AICodeSegment] = []

    for sf in source_files:
        all_signals: list[str] = []
        total_score = 0.0

        commit_score, commit_sigs = _score_commit_signals(sf.relative_path, commits)
        total_score += commit_score * 0.30
        all_signals.extend(commit_sigs)

        pattern_score, pattern_sigs = _score_code_patterns(sf.content, sf.relative_path)
        total_score += pattern_score * 0.25
        all_signals.extend(pattern_sigs)

        security_score, security_sigs = _score_security_antipatterns(sf.content)
        total_score += security_score * 0.25
        all_signals.extend(security_sigs)

        density_score, density_sigs = _score_comment_density(sf.content, sf.language)
        total_score += density_score * 0.10
        all_signals.extend(density_sigs)

        placeholder_score, placeholder_sigs = _score_placeholder_strings(sf.content)
        total_score += placeholder_score * 0.05
        all_signals.extend(placeholder_sigs)

        validity_score, validity_sigs = _score_method_validity(sf.content, sf.language)
        total_score += validity_score * 0.05
        all_signals.extend(validity_sigs)

        final_score = min(total_score, 1.0)

        if final_score >= MIN_CONFIDENCE:
            line_count = sf.content.count("\n") + 1
            segments.append(
                AICodeSegment(
                    file_path=sf.relative_path,
                    line_start=1,
                    line_end=line_count,
                    confidence=round(final_score, 3),
                    signals=all_signals,
                )
            )
            logger.debug(
                "AI code detected in %s (confidence=%.2f, signals=%d)",
                sf.relative_path,
                final_score,
                len(all_signals),
            )

    segments.sort(key=lambda s: s.confidence, reverse=True)
    logger.info("AI code detector found %d suspicious segments", len(segments))
    return segments
