"""Data models for the analysis subsystem."""

from dataclasses import dataclass, field
from typing import Any


@dataclass
class FunctionDef:
    """Represents a function or method extracted from AST analysis."""

    name: str
    start_line: int
    end_line: int
    is_async: bool
    parameters: list[str] = field(default_factory=list)


@dataclass
class APIEndpoint:
    """Represents an API endpoint detected in source code."""

    method: str        # GET, POST, PUT, DELETE, etc.
    route: str         # URL pattern
    handler_name: str
    line: int
    has_auth_decorator: bool


@dataclass
class ASTResult:
    """Results of Tree-sitter AST analysis for a single file."""

    file_path: str
    language: str
    functions: list[FunctionDef] = field(default_factory=list)
    api_endpoints: list[APIEndpoint] = field(default_factory=list)
    imports: list[str] = field(default_factory=list)
    class_names: list[str] = field(default_factory=list)
    parse_errors: list[str] = field(default_factory=list)


@dataclass
class SemgrepFinding:
    """A single finding returned by Semgrep."""

    rule_id: str
    severity: str
    file_path: str
    line_start: int
    line_end: int
    message: str
    fix_suggestion: str | None
    raw: dict[str, Any] = field(default_factory=dict)


@dataclass
class AICodeSegment:
    """A code segment identified as likely AI-generated."""

    file_path: str
    line_start: int
    line_end: int
    confidence: float     # 0.0–1.0
    signals: list[str] = field(default_factory=list)


@dataclass
class JoernFinding:
    """A single finding returned by a Joern CPG script."""

    rule_id: str
    severity: str
    file_path: str
    line: int
    method_name: str
    script: str           # which .sc script produced this
    raw: dict[str, Any] = field(default_factory=dict)


@dataclass
class DependencyFinding:
    """A known CVE found in a project dependency via OSV API."""

    package_name: str
    installed_version: str
    ecosystem: str
    cve_id: str
    severity: str
    cvss_score: float
    title: str
    description: str
    fixed_version: str
    manifest_file: str


@dataclass
class ThreatModel:
    """STRIDE threat model generated by LLM reasoning."""

    threats: list[dict[str, Any]] = field(default_factory=list)
    high_value_targets: list[str] = field(default_factory=list)
    attack_surface_summary: str = ""


@dataclass
class AttackChain:
    """A multi-step attack scenario synthesized by LLM reasoning."""

    title: str
    steps: list[str]
    finding_ids: list[str]
    combined_severity: str
    individual_severities: list[str]
    business_impact: str
    cvss_estimate: float
    proof_of_concept: str = ""
